version: "3.9"

services:

  host-app:
    build:
      context: ../host-app
    container_name: host-app
    ports:
      - "3000:80"

  user-app:
    build:
      context: ../user-app
    container_name: user-app
    ports:
      - "3001:80"

  offer-app:
    build:
      context: ../offer-app
    container_name: offer-app
    ports:
      - "3002:80"
