services:

  # Keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    command:
      - start-dev
      - --hostname=keycloak
      - --hostname-strict=false
      - --http-enabled=true
      - --http-port=8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      # KC_LOG_LEVEL: DEBUG
      # KC_LOG_CONSOLE_LEVEL: DEBUG
      # QUARKUS_LOG_CATEGORY_OrgKeycloakServer: DEBUG
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/master/.well-known/openid-configuration" ]
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3090:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: user_services
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  # MongoDB service
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: offer_services
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    networks:
      - monitoring

  # Kafka service
  kafka:
    image: 'apache/kafka:4.0.0'
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"  # optional internal listener
    environment:
      # KRaft mode enabled
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - kafka_data:/kafka/logs
    networks:
      - monitoring

  # Redis Service
  redis:
    image: redis:8.2.1
    container_name: redis
    command: [ "redis-server", "--requirepass", "mypassword" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring

  # Redis Insight
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"

  # Autoconfiguration Service
  autoconfiguration-service:
    build: ../autoconfiguration-service
    container_name: autoconfiguration-service
    ports:
      - "8761:8761"
    networks:
      - monitoring

  # Gateway Service
  gateway-service:
    build: ../gateway-service
    container_name: gateway-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - autoconfiguration-service
      - keycloak
    networks:
      - monitoring

  # User Service
  user-service:
    build: ../user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - autoconfiguration-service
      - gateway-service
      - postgres
      - redis
      - kafka
    networks:
      - monitoring

  # Offer Service
  offer-service:
    build: ../offer-service
    container_name: offer-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - autoconfiguration-service
      - gateway-service
      - redis
      - mongo
      - kafka
    networks:
      - monitoring

volumes:
  keycloak_data:
  postgres_data:
  mongo_data:
  kafka_data:
  redis_data:

networks:
  monitoring:
    name: docker_monitoring
    driver: bridge
